### ISSUE TITLE
Stuck on Updating CLI

### ISSUE THREAD

**Issue by tysoncadenhead** [serverless/cloud#101]
As of this morning, anytime I run any cloud command, I get a `Updating CLI` message. It never resolves and eventually times out, and yes -  I'm connected to the internet :P 

![Screen Shot 2022-02-07 at 9 38 16 AM](https://user-images.githubusercontent.com/355354/152820280-e0669207-44c3-4dfb-8bd5-73f225031f1b.png)

**Comment by tysoncadenhead** [comment]
I updated to the latest, but it's not giving me any more description than before

**Comment by tysoncadenhead** [comment]
Update: when I run cloud out of my dev dependencies, it's not getting stuck, so it's probably just something weird on my side

**Comment by emrahssamdan** [comment]
Hi @tysoncadenhead, are you able to get it correctly?

**Comment by tysoncadenhead** [comment]
Yep, this can be closed.
