### ISSUE TITLE
Setting timeout for tests

### ISSUE THREAD

**Issue by sd-hypredge** [serverless/cloud#116]
I have a SaaS database that I use for testing. The before and after tests  need configuration. My tests run into 
  thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

I have tried multiple options, none of which work:
a. using jest config file and setting a testTimeOut in it, both typescript and javascript
b. using jest.settimeout() in the scripts, which fail with not being able to find jest during "cloud test". This, incidentally, works fine when I run the test locally.

There needs to be a way to specify a test  timeout.
If there is, then it needs to be documented.

I am evaluating severless cloud currently, and not being able to run our tests is a deal breaker for us

**Comment by dougmoscrop** [comment]
Completely agree, @rschick can you take a look at this?

**Comment by rschick** [comment]
You should be able to use `jest.setTimeout()`, but you need to import the jest global object using 

```javascript
import { jest } from '@jest/globals';
```

**Comment by dougmoscrop** [comment]
I think we have a global timeout of 60 seconds though, right? We could consider increasing that

**Comment by sd-hypredge** [comment]
> You should be able to use `jest.setTimeout()`, but you need to import the jest global object using
> 
> ```js
> import { jest } from '@jest/globals';
> ```

Thanks @rschick , that worked. 
Would be helpful to others if this were in the docs. Closing the issue
