### ISSUE TITLE
Update installed, but your enviroment is still loading the outdated version

### ISSUE THREAD

**Issue by tobkle** [serverless/cloud#118]
Wanted to run my sandbox environment in cli shell with:

```zsh
cloud
```

Receiving suddenly the error message: 

```
x Update installed, but your enviroment is still loading the outdated version
```

tried:

```zsh
npm i @serverless/cloud@latest
npm i -g  @serverless/cloud@latest
cloud update
package.json: "@serverless/cloud": "^2.7.1"
```

But cannot start cloud any more?

Any hints?

**Comment by eahefnawy** [comment]
do you mean that every time you run `cloud` you get this message? Could you let me know how you installed the CLI originally? Did you use npx by any chance? Do you use an npm package manager?

Sorry for the bombarding you with questions, I just need to understand your environment 😅

**Comment by dougmoscrop** [comment]
Sorry about this, Tobias!  We are working on making the auto-update process more robust, as well as improving the instructions if it encounters a problem.

**Comment by tobkle** [comment]
Don't mind, that work-around with --skip-update is fine for me.
