### ISSUE TITLE
Request for angular starter

### ISSUE THREAD

**Issue by sd-hypredge** [serverless/cloud#119]
Like vue and react starters, appreciate support for angular
I am willing to create and contribute, as I am starting to adapt a react one to angular. Want to make sure no one else is on it, just to avoid duplication

Edit :
I have PR ready that gets the initial setup going for angular. I am not sure if you are willing to merge a PR form an external person, but if you are, then please create branch and I will push to that branch.

**Comment by dougmoscrop** [comment]
Contributions are welcome!  We are working on improved support for a few frameworks beyond just examples, as well, but Angular was not part of that so happy to work from whatever you can help us out with!

**Comment by sd-hypredge** [comment]
@dougmoscrop  Looks like your own dev process is based on feature branches, so it would be helpful if there is a feature branch that I can do a pull request on. Once you have a feature branch in place, let me know the name/ details , and I can do a pull request. Appreciate the quick response

**Comment by dougmoscrop** [comment]
Sure, will do in the morning!

**Comment by sd-hypredge** [comment]
> I created a branch, `angular-starter`, with nothing in it - but don't worry about our process too much

Pull request in place.
