### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by sd-hypredge** [serverless/cloud#121]
I am getting this error running my tests, and have no clue whats causing this.  
Seems like a timeout, but I don't see any literature or docs on timeout limits or such while running tests

To quote the documentation
> Unit tests could in theory run in your local development environment instead of in your developer sandbox, but we recommend that you run all unit and integration tests using the cloud test command instead, to simplify your project.

Question: What volume/duration of tests can I reasonably run on your platform ? 

✔ Test instance started: https://powerful-data-izo1o.cloud.serverless.com
Error: waitForEvent timed out
    at Timeout._onTimeout (/Users/sdas/project/node_modules/@serverless/cloud/dist/index.js:66820:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
✖ Error: waitForEvent timed out
✔ Test instance deleted

**Comment by dougmoscrop** [comment]
Apologies, this is a misconfiguration between how long the CLI is willing to wait for the event that says the test completed, and how long the tests can run for.  We will get these in sync.

In terms of volume, @jeremydaly can weigh in but I think it will boil down to "what you're willing to pay for" since it would just be billed based on usage;  for duration, we could be more flexible up to the 15 minute lambda limit

**Comment by sd-hypredge** [comment]
Glad to know, and will wait for this to get fixed
Being able to run my tests straight up in serverless has been valuable, as I dont have to spend time jumping across local and remote environments to ensure it all works. So it is definitely valuable and worth paying for, though its hard to quantify. 

Beyond that, from a technical standpoint, some large projects accumulate an hour or so worth of automated integration tests. If the tests are constrained to a single invokation of a lambda for example, then it may be scale bottleneck in the long run.

**Comment by sd-hypredge** [comment]
I have gotten to a stage where my integration tests don't finish any more. Is there an ETA for fixing this ?

**Comment by dougmoscrop** [comment]
Hey, I am working right now on trying to help unlock you by supporting longer runs, and I hope we can get to some bigger more ambitious changes to testing very soon

**Comment by dougmoscrop** [comment]
As of CLI 2.8.1, it should wait up to 5 minutes, with the ability to bump that up further pending a rollout on our side - does that help you in the short term?

**Comment by sd-hypredge** [comment]
Thanks, this works great.
Closing as it is not an issue any more
