### ISSUE TITLE
Need control of jest test concurrency

### ISSUE THREAD

**Issue by sd-hypredge** [serverless/cloud#122]
I have a Data Abstraction Layer (DAL) that interfaces with a remote saas database, and an service layer that interfaces with the DAL. Each test does its thing and drop the entire dataset. I have the DAL and the api tests in separate files, and seems that they end up running in parallel, and stepping on each other's toes. 

If I have better control on the tests, like run them in sequence (--runInBand jest command line option), it helps with this problem
I can alternately separate out my data into DAL test and api test, I only have one DB instance ( tight budget) and I am unwilling to buy DB separation

Any suggestions/ options ?

**Comment by dougmoscrop** [comment]
It makes sense, I'm honestly not sure if we want to keep forcing you in to Jest (we have started talking a bit about Vitest internally), or just make this a more abstract sort of test runner where you can call `cloud test [pattern1] [pattern2], etc.` and we just concurrently run each of those patterns by invoking `npm t [pattern]` in a separate thing - that way you'd be able to control concurrency down to 1 if you want, specify your own arguments like --runInBand, and so on.  Would that be of any interest to you?

**Comment by sd-hypredge** [comment]
It works best if I don't need to know the internals of jest to use serverless cloud . I would definitely prefer "cloud test [pattern1]" etc metaphor. Just to make the point... I had to spent time learning and understanding basic jest just to even try to tweak some basic functionality.
