### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by sd-hypredge** [serverless/cloud#123]
This started to appear all of a sudden today... Not sure what the issue is, and what the fix is.
My development team is held up on this for hours now

17:51:16 ─   Module /tmp/task in the setupFilesAfterEnv option was not found.
17:51:16 ─ 
17:51:16 ─ ● Validation Error:
17:51:16 ─ 
17:51:16 ─   Configuration Documentation:
17:51:16 ─   https://jestjs.io/docs/configuration
17:51:16 ─          <rootDir> is: /tmp/task
17:51:16 ─

**Comment by dougmoscrop** [comment]
Can you tell us more about your project configuration? cjs or ESM? JS or typescript?

**Comment by dougmoscrop** [comment]
Or an org name

**Comment by sd-hypredge** [comment]
hypredge

**Comment by sd-hypredge** [comment]
setupFilesAfterEnv seems to be a jest configuration option

**Comment by dougmoscrop** [comment]
Thanks, ok we will look at your instance to be sure, but I have an idea of what causes this regression and we will fix it ASAP, and make sure to cover the gap that missed this in our automated tests

**Comment by sd-hypredge** [comment]
Is there a workaround that lets me continue ? I am guessing you folks pushed a change, can you not rollback till you fix this?

**Comment by sd-hypredge** [comment]
Seem to be fixed now. Closing issue
