### ISSUE TITLE
deploy cli command fails

### ISSUE THREAD

**Issue by sd-hypredge** [serverless/cloud#148]
I have an application that works fine with the personal instance. However the command "deploy" on cli fails, and there doesnt seems to be a log/output that points me to what went wrong

My instance details as below 
 https://lightning-stack-cn0lr.cloud.serverless.com is the personal instance
https://brave-api-uamsm.cloud.serverless.com ins the instance I want to deploy to production 

appreciate help on this

**Comment by rschick** [comment]
We're working on adding build logs to the dashboard. In the meantime, can you try running the build locally using `cloud run build`, or just `run build` inside the cloud shell, and see if it surfaces the build errors?

**Comment by sd-hypredge** [comment]
I didnt find the issue, but it went away once I killed my angular live server.
