### ISSUE TITLE
TypeScript Enhancement: data.set<T>

### ISSUE THREAD

**Issue by 403access** [serverless/cloud#172]
Hello all together!

Wanted to ask whether the `interface` of `Data` can be slightly modified?

As an example, let's see the following problem.

As of now, one of the `set` method signatures looks like that:
````javascript
set<T>(keys: string, value: any, opts?: setOptions | boolean): Promise<SetResponse<T>>
````
Instead, it should be:
````javascript
set<T>(keys: string, value: T, opts?: setOptions | boolean): Promise<SetResponse<T>>
````

It's fatal using `any` as it leads to skipping the actual type safety of TypeScript:
````javascript
const user = await data.get<User>("userDataPath")
user.someProperty = someValue
// ✅ Expected to not raising any compiler errors:
await data.set<User>("userDataPath", user)

const noUser = {
  aPropertyThatUserDoesntHave: 2
}
// 🚫 Expected to throw compiler errros:
await data.set<User>("userDataPath", noUser)
````

Thanks and have a nice day / night whereever you are located right now :)

**Comment by benminer** [comment]
Totally, will take care of this. Thanks for submitting!
