### ISSUE TITLE
Serverless cloud clone 'Timed Out'

### ISSUE THREAD

**Issue by abzork** [serverless/cloud#174]
Hello, I am trying to clone a serverless project's prod stage locally to start work on it.

prod was created by a different developer, and I am now trying to clone it so I can start working on it. I have admin access in the organisation.

However the process keeps failing with a "timed out" error. 
Exact error response is 

> "✖ Timed out waiting for operation to complete: 01GBJKS2NPYBSAT4A3DA4R3G58"
> "✖ Clone command failed"

Can you please check what's going on? 
I am cloning using the below command 
`npx cloud clone @myorg/my-app/prod`

I am able to clone my own work instance, that I created, but not the instance that other dev has created or any of the prod, beta and other stage instances. I have tried several times over last 24 hours but it keeps giving the same error.

I have searched for this issue on the internet but I couldn't find anything relating to this issue, and so I am posting it here.

Node version v16.160
Framework Core: 3.19.0
Plugin: 6.2.2
SDK: 4.3.2
Serverless cloud version : v2.10.14

Any help would be appreciated. 
Thanks in advance!

**Comment by rschick** [comment]
Thanks for reporting this, we're taking a look.

**Comment by rschick** [comment]
@abzork This is an issue on our end. The clone operation is failing when trying to copy files in storage from the source to the the target instance. We are working on a fix and will update here when a fix is ready.

As a work around, you can clone another instance that doesn't have as many files in storage. If you need storage files in your instance, you can manually download them from the source instance and upload them to the target instance.

**Comment by abzork** [comment]
Thanks for your advice, 
I was able to ask the previous team to manually send their working copy. However I am facing another error from serverless when I try to deploy it to an instance. I have posted it on a different thread.

**Comment by emrahssamdan** [comment]
Hi @abzork, this issue should be resolved now. Could you please check and confirm?
