### ISSUE TITLE
How to run app in offline? 

### ISSUE THREAD

**Issue by Lancer92** [serverless/cloud#26]

**Comment by jeremydaly** [comment]
Hi @Lancer92! Your code instantly syncs to your personal development instance in the cloud, allowing you to develop/debug your application using a copy of the cloud infrastructure your production application runs on. This avoids the need to run the app offline so you don’t need to worry about local mocking which can cause fidelity issues.

**Comment by Lancer92** [comment]
Hi @jeremydaly !
My regards, this is awesome approach.
As I have noticed, serverless cloud uses a lot of best practices, so I decided to try it out.

But what about to following **Clean architecture** - and be able to run app by providing other api (express) and data (In Memory, Redis) as infrastructure? this will allows to have some fast tests. I need it mostly because now I faced some problems with Serverless Cloud.
1. Long deployment - up to 20s. This may be due to syncing dev dependecies to a serverless cloud. Is it possible to avoid some npm's (mostly dev and its dependecies) from node_modules to be synced? This will also help to have bigger codebase & prod dependencies, as there are limit 128mb per service. ([There was a similar stackoverflow question related to heroku 8y ago](https://stackoverflow.com/questions/17929002/is-it-possible-to-have-a-separate-node-modules-folder-for-devdependencies))
2. Sometimes no debug logs and have `Internal Server Error`. https://github.com/serverless/cloud/issues/29

**Comment by jeremydaly** [comment]
Hi @Lancer92! Thanks for the feedback and the questions. We just released an update to our syncing module that should get the syncing down to less than 1 second for most code changes. Larger files will be limited by connection speed. We're also aware of the `/tmp/task` issue and have released a fix.

In terms of using Express, we are also about to launch "Bring your own framework (BYOF)" support that will allow you to use most HTTP frameworks like Express, Koa, Fastify, etc. We don't have Redis support yet, but Serverless Data is a very fast key/value datastore that is backed by DynamoDB without all the interface complexity.
