### ISSUE TITLE
Invalid instance name for google auth users whose name contains a dot

### ISSUE THREAD

**Issue by bencao** [serverless/cloud#31]
Hi team,

I got the following error when login with my google suite. Assume the user name is `jack.susan@mycompany.com`

When I try `cloud` in an established cloud project directly I got the following error:

```
✖ Invalid instance name "jack.susan". Instance name must consist only of lowercase characters and hyphens
✖ Canceled
```

**Comment by jeremydaly** [comment]
Hi @bencao! Thanks for reporting this. Users should _not_ be able to create organization names that contain a dot, so this same restriction was ported over to Serverless Cloud as we integrate with the main Serverless.com authorization system. We are investigating how this was possible and will have a fix soon.

**Comment by emrahssamdan** [comment]
This issue has been resolved.
