### ISSUE TITLE
Sync problems. Looks like caching works buggy and/or some condition expression has typo

### ISSUE THREAD

**Issue by Lancer92** [serverless/cloud#34]
File that is updated often is not synced. It caused syncing, but looks like other files are synced.
It syncs change in one small file always in 3-5 seconds, but not actually of this file is get synced.
I tried to disable autosave 'on focus lost' in vscode, and when saving manually with cmd+s but it is not syncing correctly files too.
Sometimes I receive even old version of some file. I started to add to a files console.log(filename, fileVersion), and when doing some parallel requests and the old versions sometime is called. https://share.getcloudapp.com/eDuRqgd5, https://share.getcloudapp.com/bLuqEx62

**Comment by jeremydaly** [comment]
Hi @Lancer92! What version of the CLI are you using? We released a bug fix the other day.

**Comment by Lancer92** [comment]
> Hi @Lancer92! What version of the CLI are you using? We released a bug fix the other day.
2.2.1

**Comment by jeremydaly** [comment]
Thanks, @Lancer92. We're investigating.

**Comment by emrahssamdan** [comment]
Hi Lancer, Could you please provide your org-name and the URL of your instance? We'll need those to further investigate the issue.

**Comment by rschick** [comment]
@Lancer92 are you using Typescript?

**Comment by Lancer92** [comment]
> @Lancer92 are you using Typescript?

yes
> Hi Lancer, Could you please provide your org-name and the URL of your instance? We'll need those to further investigate the issue.

provided in Slack
