### ISSUE TITLE
Route level middleware not works in serverless cloud api

### ISSUE THREAD

**Issue by Lancer92** [serverless/cloud#35]
example
```
// 'hi' is returned to a response, but logs are clear
api.get('/', (req, res, next) => next(console.log('>=[')), (req, res) => res.send('hi'))
```
Actually only called last callback, and this example from docs with cors() is not working https://www.serverless.com/cloud/docs/apps/api#middleware

**Comment by jeremydaly** [comment]
Thanks for the report! We made some modifications to the inline middleware handling the other day and this may have caused a regression. Investigating.

**Comment by emrahssamdan** [comment]
This issue has been resolved.
