### ISSUE TITLE
Is it possible to avoid downtime & 300 seconds timeout for a first requests after syncing?

### ISSUE THREAD

**Issue by Lancer92** [serverless/cloud#36]
logs: 
`2021-09-30T14:22:53.940Z ...-200299b7e141 Task timed out after 300.10 seconds`
response: 
`503 {"message":"Service Unavailable"}`

**Comment by emrahssamdan** [comment]
Hi @Lancer92, I understood sync is not timing out but the requests coming to your personal instances are timing out, right? Could you please provide your org-name and personal instance URL for lettting us investigate closely?

**Comment by Lancer92** [comment]
> please provide your...
I answered you in twitter

**Comment by dougmoscrop** [comment]
Sync should not incur any downtime, i will investigate. Thanks.

**Comment by dougmoscrop** [comment]
Just to keep you in the loop, I've reproduced this independently of your project and I am working on a solution.
