### ISSUE TITLE
"Serverless Cloud CLI auto update failed" on latest version (v2.5.6)

### ISSUE THREAD

**Issue by DMeechan** [serverless/cloud#63]
The CLI was working fine for me ~1 hour ago on v2.5.5. Since then, v2.5.6 has been released and auto update doesn't seem to be working properly.

I've updated from v2.5.5 to the latest version (v2.5.6):

```bash
npm i -g @serverless/cloud
/Users/USERNAME/.nvm/versions/node/v14.18.1/bin/cloud -> /Users/USERNAME/.nvm/versions/node/v14.18.1/lib/node_modules/@serverless/cloud/bin/bin
+ @serverless/cloud@2.5.6
updated 1 package in 2.945s
```

And have confirmed that the package version in`.../@serverless/cloud/` is `2.5.6`

However, every command results in the same error message "Serverless Cloud CLI auto update failed":

```bash
$ ~/project (master)> cloud deploy

✖ Serverless Cloud CLI auto update failed. You are currently running v2.5.5. Please manually update the CLI to the latest version (v2.5.6) to proceed.

$ ~/project (master)> cloud help

✖ Serverless Cloud CLI auto update failed. You are currently running v2.5.5. Please manually update the CLI to the latest version (v2.5.6) to proceed.

$ ~/project (master)> cloud version

✖ Serverless Cloud CLI auto update failed. You are currently running v2.5.5. Please manually update the CLI to the latest version (v2.5.6) to proceed.
```

**Comment by jeremydaly** [comment]
Thanks for the report. We are investigating this.

**Comment by jeremydaly** [comment]
@DMeechan - The issue has been resolved. Please try running the `cloud` command again and that should update you to version `2.5.7`. Please let us know if you have any other issues.
