### ISSUE TITLE
frontend ignored

### ISSUE THREAD

**Issue by SteveDeWald** [serverless/cloud#80]
Hello,

I followed the workflow in the Serverless Cloud docs to fork the `cloud-chat` app and get started.  The cloud-chat readme refers to a `frontend/.env.development`, but the frontend folder wasn't checked out when I forked the app.

I'm guessing the issue has something to do with the frontend folder being included in the `.serverlessignore` file.

Cheers.

**Comment by dougmoscrop** [comment]
You're right, this is a gap in how the ignore + fork aspects interact which we need to fix.  In the mean time, you can see the code for that example project here: https://github.com/serverless/cloud/tree/main/examples/cloud-chat/frontend

**Comment by jeremydaly** [comment]
If you clone from the example project, be sure to replace the `package.json` from your forked version and it will connect to the app you've already created.

**Comment by SteveDeWald** [comment]
Thanks for the quick responses.

> If you clone from the example project, be sure to replace the `package.json` from your forked version and it will connect to the app you've already created.

Ha, I just figured that out and was about to suggest adding that to the readme.  It's working now, thanks!

**Comment by dougmoscrop** [comment]
Sorry about that, we are definitely going to make this better!
